name: NEXORA Robot

on:
  workflow_dispatch:

jobs:
  run-nexora-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Executar NEXORA Robot
        run: python robot/nexora_robot.py
